# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DiagramSdk/Automation/DiagramSdk.Automation.Protocols/Identifiers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DiagramSdk/Automation/DiagramSdk.Automation.Protocols/Identifiers.proto',
  package='national_instruments.diagram_sdk.automation.protocols',
  syntax='proto3',
  serialized_options=b'\252\0023NationalInstruments.DiagramSdk.Automation.Protocols',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nGDiagramSdk/Automation/DiagramSdk.Automation.Protocols/Identifiers.proto\x12\x35national_instruments.diagram_sdk.automation.protocols\"\'\n\x11ProjectIdentifier\x12\x12\n\nproject_id\x18\x01 \x01(\t\"b\n\x11\x45lementIdentifier\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x12\n\nelement_id\x18\x03 \x01(\t\x12\x12\n\nsubpart_id\x18\x04 \x01(\tB6\xaa\x02\x33NationalInstruments.DiagramSdk.Automation.Protocolsb\x06proto3'
)




_PROJECTIDENTIFIER = _descriptor.Descriptor(
  name='ProjectIdentifier',
  full_name='national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier.project_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=169,
)


_ELEMENTIDENTIFIER = _descriptor.Descriptor(
  name='ElementIdentifier',
  full_name='national_instruments.diagram_sdk.automation.protocols.ElementIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='national_instruments.diagram_sdk.automation.protocols.ElementIdentifier.project_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='national_instruments.diagram_sdk.automation.protocols.ElementIdentifier.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='element_id', full_name='national_instruments.diagram_sdk.automation.protocols.ElementIdentifier.element_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subpart_id', full_name='national_instruments.diagram_sdk.automation.protocols.ElementIdentifier.subpart_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=269,
)

DESCRIPTOR.message_types_by_name['ProjectIdentifier'] = _PROJECTIDENTIFIER
DESCRIPTOR.message_types_by_name['ElementIdentifier'] = _ELEMENTIDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectIdentifier = _reflection.GeneratedProtocolMessageType('ProjectIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTIDENTIFIER,
  '__module__' : 'DiagramSdk.Automation.DiagramSdk.Automation.Protocols.Identifiers_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier)
  })
_sym_db.RegisterMessage(ProjectIdentifier)

ElementIdentifier = _reflection.GeneratedProtocolMessageType('ElementIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTIDENTIFIER,
  '__module__' : 'DiagramSdk.Automation.DiagramSdk.Automation.Protocols.Identifiers_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.diagram_sdk.automation.protocols.ElementIdentifier)
  })
_sym_db.RegisterMessage(ElementIdentifier)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
