"""List of event names."""

ALARM_ADDED = "Active Alarm Added"
ALARM_REMOVED = "Active Alarm Removed"
ALARM_CHANGED = "Active Alarm Changed"
ALARM_CLEARED = "Alarm Cleared and Acknowledged"
LOG_FILE_CREATED = "Log File Created"
LOG_FILE_CLOSED = "Log File Closed"
TEST_STARTED = "Test Started"
TEST_PAUSED = "Test Paused"
TEST_RESUMED = "Test Resumed"
TEST_STOPPED = "Test Stopped"
