# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigurationBasedSoftware/FlexLogger/Automation/FlexLogger.Automation.Protocols/FlexLoggerApplication.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flexlogger.DiagramSdk.Automation.DiagramSdk.Automation.Protocols import Identifiers_pb2 as DiagramSdk_dot_Automation_dot_DiagramSdk_dot_Automation_dot_Protocols_dot_Identifiers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigurationBasedSoftware/FlexLogger/Automation/FlexLogger.Automation.Protocols/FlexLoggerApplication.proto',
  package='national_instruments.flex_logger.automation.protocols',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nlConfigurationBasedSoftware/FlexLogger/Automation/FlexLogger.Automation.Protocols/FlexLoggerApplication.proto\x12\x35national_instruments.flex_logger.automation.protocols\x1aGDiagramSdk/Automation/DiagramSdk.Automation.Protocols/Identifiers.proto\"*\n\x12OpenProjectRequest\x12\x14\n\x0cproject_path\x18\x01 \x01(\t\"p\n\x13OpenProjectResponse\x12Y\n\x07project\x18\x01 \x01(\x0b\x32H.national_instruments.diagram_sdk.automation.protocols.ProjectIdentifier2\xc0\x01\n\x15\x46lexLoggerApplication\x12\xa6\x01\n\x0bOpenProject\x12I.national_instruments.flex_logger.automation.protocols.OpenProjectRequest\x1aJ.national_instruments.flex_logger.automation.protocols.OpenProjectResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[DiagramSdk_dot_Automation_dot_DiagramSdk_dot_Automation_dot_Protocols_dot_Identifiers__pb2.DESCRIPTOR,])




_OPENPROJECTREQUEST = _descriptor.Descriptor(
  name='OpenProjectRequest',
  full_name='national_instruments.flex_logger.automation.protocols.OpenProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_path', full_name='national_instruments.flex_logger.automation.protocols.OpenProjectRequest.project_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=282,
)


_OPENPROJECTRESPONSE = _descriptor.Descriptor(
  name='OpenProjectResponse',
  full_name='national_instruments.flex_logger.automation.protocols.OpenProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='national_instruments.flex_logger.automation.protocols.OpenProjectResponse.project', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=396,
)

_OPENPROJECTRESPONSE.fields_by_name['project'].message_type = DiagramSdk_dot_Automation_dot_DiagramSdk_dot_Automation_dot_Protocols_dot_Identifiers__pb2._PROJECTIDENTIFIER
DESCRIPTOR.message_types_by_name['OpenProjectRequest'] = _OPENPROJECTREQUEST
DESCRIPTOR.message_types_by_name['OpenProjectResponse'] = _OPENPROJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenProjectRequest = _reflection.GeneratedProtocolMessageType('OpenProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENPROJECTREQUEST,
  '__module__' : 'ConfigurationBasedSoftware.FlexLogger.Automation.FlexLogger.Automation.Protocols.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.OpenProjectRequest)
  })
_sym_db.RegisterMessage(OpenProjectRequest)

OpenProjectResponse = _reflection.GeneratedProtocolMessageType('OpenProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPENPROJECTRESPONSE,
  '__module__' : 'ConfigurationBasedSoftware.FlexLogger.Automation.FlexLogger.Automation.Protocols.FlexLoggerApplication_pb2'
  # @@protoc_insertion_point(class_scope:national_instruments.flex_logger.automation.protocols.OpenProjectResponse)
  })
_sym_db.RegisterMessage(OpenProjectResponse)



_FLEXLOGGERAPPLICATION = _descriptor.ServiceDescriptor(
  name='FlexLoggerApplication',
  full_name='national_instruments.flex_logger.automation.protocols.FlexLoggerApplication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenProject',
    full_name='national_instruments.flex_logger.automation.protocols.FlexLoggerApplication.OpenProject',
    index=0,
    containing_service=None,
    input_type=_OPENPROJECTREQUEST,
    output_type=_OPENPROJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLEXLOGGERAPPLICATION)

DESCRIPTOR.services_by_name['FlexLoggerApplication'] = _FLEXLOGGERAPPLICATION

# @@protoc_insertion_point(module_scope)
